---
title: "filter"
author: "Gabe"
date: "July 10, 2015"
output: html_document
---

```{r}
limitedsites=function(vcf){
     a <- alt(vcf)
     altSnp <- elementLengths(a) == 1L
     ai <- unlist(a[altSnp]) # #unlist DNAstringsets
     altSnp[altSnp] <- nchar(ai) == 1L & (ai %in% "G"
                                          )
     g <- alt(vcf)
     altSnp2 <- elementLengths(g) == 1L
     gi <- unlist(g[altSnp2]) # #unlist DNAstringsets
     altSnp2[altSnp2] <- nchar(gi) == 1L & (gi %in% "A")
  
     t <- alt(vcf)
     altSnp3 <- elementLengths(t) == 1L
     ti <- unlist(t[altSnp3]) # #unlist DNAstringsets
     altSnp3[altSnp3] <- nchar(ti) == 1L & (ti %in% "C")
    
     c <- alt(vcf)
     altSnp4 <- elementLengths(c) == 1L
     ci <- unlist(a[altSnp4]) # #unlist DNAstringsets
     altSnp4[altSnp4] <- nchar(ci) == 1L & (ci %in% "T")
    
     vcf[((altSnp & ref(vcf) == "A")) | ((altSnp2 & ref(vcf) == "G")) | ((altSnp3 & ref(vcf) == "T")) | ((altSnp4 & ref(vcf) == "C"))]
    
}


```

```{r}
source("http://bioconductor.org/biocLite.R")
biocLite("VariantAnnotation") 
library("VariantAnnotation")

limitedvcf=limitedsites(vcf)

```






